[book]
authors = ["xinxiamu"]
language = "en"
multilingual = false
src = "src"
title = "Spring Cloud Alibaba微服务架构"

[output.html]
git-repository-url = "https://gitee.com/ym-architecture/mspring-cloud-alibaba"

[rust]
edition = "2021"
